// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using proyecto_pabon_yilber.Data;

#nullable disable

namespace proyecto_pabon_yilber.Migrations
{
    [DbContext(typeof(dbcontex))]
    [Migration("20251119142021_migration_003")]
    partial class migration_003
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("proyecto_pabon_yilber.Models.Usuariomodel", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("Usuario_Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_Contrasena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_Salt")
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
